loja_cadastro_produtos/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('my_aplication.urls')),
    path('admin/', admin.site.urls),
]

my_aplication/urls.py
from django.urls.conf import path
from django.urls import path
from . import views
urlpatterns = [
    path('', views.cadastrar_produtos, name='home'),
    path('deletar/<int:id>/', views.deletar_produto, name='deletar'),
    path('<int:id>/', views.editar_produto, name='editar'),
]

loja_cadastro_produtos/models.py
from django.db import models

class Produto(models.Model):
    nome = models.CharField(max_length=40, null=False, blank=False)
    preco_do_produto = models.DecimalField(max_digits=5, blank=False, decimal_places=2)
    marca_do_produto = models.CharField(max_length=40, blank=False)
    

my_aplication/forms.py
from django import forms
from django.core import validators
from loja_cadastro_produtos.models import Produto

class ProdutoForms(forms.ModelForm):
    class Meta:
        model = Produto
        fields = ['nome', 'preco_do_produto', 'marca_do_produto']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'preco_do_produto': forms.TextInput(attrs={'class': 'form-control'}),
            'marca_do_produto': forms.TextInput(attrs={'class': 'form-control'})
        }

   
    

my_aplication/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from my_aplication.forms import ProdutoForms
from loja_cadastro_produtos.models import Produto
from django.contrib import messages


#Criando e Listando produtos
def cadastrar_produtos(request):
    listar = Produto.objects.all()
    if request.method == "POST":
        form = ProdutoForms(request.POST)
        if form.is_valid():
            nm = form.cleaned_data["nome"]
            pc = form.cleaned_data["preco_do_produto"]
            mp = form.cleaned_data["marca_do_produto"]
            cadastrar = Produto(nome=nm, preco_do_produto=pc, marca_do_produto=mp)
            cadastrar.save()
            messages.success(request, 'Produto adcionado com sucesso')
    else:
        form = ProdutoForms()
    return render(request, 'html/cadastro_produto.html', {'form': form, 'listar': listar, 'message': messages})


#editar Produto
def editar_produto(request, id):
    produto = Produto.objects.get(pk=id)
    if request.method == 'POST':
        form = ProdutoForms(request.POST, instance=produto)
        if form.is_valid():
            form.save()
            atualizado = messages.success(request, 'Produto atualizado com sucesso!')
        else:
            produto = Produto.objects.get(pk=id)
    form = ProdutoForms(instance=produto)
    return render(request, 'html/editar_produto.html', {'produto': produto, 'form': form})


#deletndo produtos
def deletar_produto(request, id):
    if request.method == 'POST':
        produto = Produto.objects.get(pk=id)
        produto.delete()
        excluir = messages.warning(request, 'Excluído com sucesso')
        return HttpResponseRedirect('/', {'excluir': excluir})
    

my_aplication/templates/base.html
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>
    {% block title %} 
    {% endblock title %}
    </title>
  </head>
  <body>
  
    <div class="container mt-5">
      <h2 class="text-center alert alert-danger">Cadastro e listagem de produtos</h2> 
      {% block content %}
    
      {% endblock content %}
    </div>
      

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

my_aplication/templates/html/cadastro_produto.html
{% extends "base.html" %}

{% block title %} Cadastro de produtos {%  endblock title %}

{% block content %} 

<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="text-center alert alert-info">Cadastro de produtos</h4>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} fade show" role="alert" id="success-alert">
                    {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span
                </button>
                </div>
            {% endfor %}
        {% endif %}
      <div>
        <form method="post" action="{% url 'home'%}">{% csrf_token %}
            <p>
                <label for="id_nome">Nome:</label> 
                <input type="text" name="nome" class="form-control" maxlength="40" required="" id="id_nome">
            </p>
            <p>
                <label for="id_preco_do_produto">Preco do produto:</label> 
                <input type="text" name="preco_do_produto" class="form-control" required="" id="id_preco_do_produto">
            </p>
            <p>
                <label for="id_marca_do_produto">Marca do produto:</label> 
                <input type="text" name="marca_do_produto" class="form-control" maxlength="40" required="" id="id_marca_do_produto">
            </p>

            <input type="submit" value="Adicionar" class="btn btn-success">
        </form>
        </div>
    </div>
    <div class="col-sm-8">
      <h4 class="text-center alert alert-info">Tabela de produtos</h4>
      {% if listar %}
      <div> 
      <table class="table table-hover">
            <thead class="thead-light">
                <tr>
                <th scope="col">ID</th>
                <th scope="col">Nome</th>
                <th scope="col">Valor</th>
                <th scope="col">Marca</th>
                <th scope="col">Ação</th>
                </tr>
            </thead>
            <tbody>
                {% for item in listar %}
                
                    <tr>
                    <th scope="row">{{item.id}}</th>
                    <td>{{item.nome}}</td>
                    <td>{{item.preco_do_produto}}</td>
                    <td>{{item.marca_do_produto}}</td>
                    <td>
                        <a href="{% url 'editar' item.id%}"class="btn btn-warning btn-sm">Editar</a>
                        <form action="{% url 'deletar' item.id %}" method="post" class="d-inline">{% csrf_token %}
                            <input type="submit" class="btn btn-danger" value="Deletar">
                        </form>
                    </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
      </div>
      {% endif %}
    </div>
</div>
{% endblock content %}

my_aplication/templates/html/editar_produto.html
{% extends "base.html" %}

{% block title %} Editar de produtos {%  endblock title %}

{% block content %} 
    <div class="row">
        <div class="col-sm-8 offset-2">
            <h1 class="text-center alert alert-info">Atualizar produto</h4>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} fade show" role="alert" id="msg">
                        {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span
                    </button>
                    </div>
                {% endfor %}
            {% endif %}
            <form action="" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Atualizar" class="btn btn-success">
                <a href="{% url 'home'%}"class="btn btn-light btn-sm">voltar</a>
            </form>
        </div>
    </div>
{% endblock content %}

my_aplication/templates/html/index.html
<!doctype html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <h1>{{h}}!</h1>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->
  </body>
</html>